# Generated by Django 5.0.1 on 2024-11-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProductos', '0002_categoria_productos_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
